[package]
name = "hello_world"
version = "0.1.0"
authors = ["Bruce Zhang <zongtongguilai1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "hello_world"
path = "src/hello_world.rs"
[dependencies]
